name: ci

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    
    env:
      HUGO_VERSION: 0.144.1
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ env.HUGO_VERSION }}

      - name: Build the app
        run: hugo --minify
      
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get tag for Docker image
        run: |
            git fetch --tags
            echo "Tags fetched"
            TAG=$(git describe --tags `git rev-list --tags --max-count=1` | sed 's/^v//')
            echo "tag=$TAG" >> $GITHUB_OUTPUT
            echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            daisukebtw/hugo-blog:${{ env.TAG }}
            daisukebtw/hugo-blog:latest
        
      - name: Checkout configuration repository
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.K8S_CONFIG_REPO }}
          token: ${{ secrets.K8S_CONFIG_REPO_TOKEN }}
          ref: main

      - name: Update Kubernetes manifest
        run: |
          MANIFEST=prod/deployment.yaml
          IMAGE_NAME=daisukebtw/hugo-blog
          sed -i "s|image: .*|image: $IMAGE_NAME:$TAG|" $MANIFEST
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add $MANIFEST 
          git commit -m "Update Docker image versions [skip ci]"
      
      - name: Push changes
        run: git push
